language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests -p *_test.py
after_success:
  - coveralls